version: '2'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "2010:8069"
    volumes:
      - ./odoo-web-data:/var/lib/crism
      - ./config:/etc/odoo
      - ./odoo-extra-addons:/mnt/extra-addons
      - ./CRI-SM:/mnt/crism
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgcrism
volumes:
  odoo-web-data:
  odoo-db-data:

